version: '3.8'

services:
  ml:
    build: ./ml
    ports:
      - "5001:5001"
    restart: unless-stopped

  backend:
    build: ./backend
    ports:
      - "4000:4000"
    depends_on:
      - ml
    environment:
      - ML_API_URL=http://ml:5001

  ui:
    build: ./ui
    depends_on:
      - backend
    ports:
      - "3001:80"
